macro(build_documentation DOCUMENTATION_NAME)
    set(RELATIVE_DESTINATION_DIR html)
    set(ABSOLUTE_DESTINATION_DIR ${CMAKE_SOURCE_DIR}/${RELATIVE_DESTINATION_DIR})
    set(FILES)

    file(GLOB_RECURSE FILES RELATIVE ${ABSOLUTE_DESTINATION_DIR}
        ${ABSOLUTE_DESTINATION_DIR}/*.css
        ${ABSOLUTE_DESTINATION_DIR}/*.html
        ${ABSOLUTE_DESTINATION_DIR}/*.jpg
        ${ABSOLUTE_DESTINATION_DIR}/*.js
        ${ABSOLUTE_DESTINATION_DIR}/*.php
        ${ABSOLUTE_DESTINATION_DIR}/*.png
    )

    foreach(FILE ${FILES})
        get_filename_component(DESTINATION_DIR ${CMAKE_BINARY_DIR}/${RELATIVE_DESTINATION_DIR}/${ARGN}/${FILE} DIRECTORY)

        file(COPY ${ABSOLUTE_DESTINATION_DIR}/${FILE} DESTINATION ${DESTINATION_DIR})
    endforeach()
endmacro()
